import type { Metadata } from 'next'
import '@/app/globals.css'
import Navbar from '@/components/navbar'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <div>
            <Navbar />
            {children}
        </div>
    )
}
